
<table>
    <tr>
        <th>ID</th>
        <th>PRICE</th>
        <th>NAME</th>
        <th>VENDOR</th>
    </tr>
    <?php foreach($this->list as $item): ?>
        <tr>
            <td><?php echo $item['id']; ?></td>
            <td><?php echo $item['price']; ?></td>
            <td><?php echo $item['name']; ?></td>
            <td><?php echo $item['vendor_id']; ?></td>
        </tr>
    <?php endforeach; ?>
</table>